### ISSUE TITLE
Web app Svelte - navigator.userAgent deprecated ?

### ISSUE THREAD

**Issue by sdgalvan** [starknet-io/get-starknet#169]
Hello! I don't know if it's ok to open an issue for this, but I wanted to comment on it if applicable, apparently if you have a svelte app using get-starknet, only one of the two wallets can be used because userAgent is deprecated by Chrome. From what I could see it is being used in the Modal.svelte:
![image](https://user-images.githubusercontent.com/58611754/207182089-e129e56c-7fb0-418e-b036-5142859326b0.png)

This is the warning I see in the browser:
![image](https://user-images.githubusercontent.com/58611754/207182152-2cb5276b-f6f8-4747-b284-a1938170fdd9.png)

And the problem (i think) is that it is not detected to have Braavos installed, I am investigating to find some alternative way or to solve the problem.
![image](https://user-images.githubusercontent.com/58611754/207182160-79b7a40d-43bf-4ad0-98b5-3d4ed5315128.png)

Dependencies (tried different versions of both starknet and get-starknet 2.0.0 doesn't work either):
![image](https://user-images.githubusercontent.com/58611754/207183647-5f801c95-4179-4f20-a13f-f18da0a222b8.png)

**Comment by avimak** [comment]
@sdgalvan tnx, could u pls provide a repo with a minimal set for reproducing the bug on my end?

**Comment by sdgalvan** [comment]
Hi avimak! Thank you for response, make this PR in my repository. You can clone an use this [PR with minimal set](https://github.com/sdgalvan/pokemon-cairo/pull/4).

**Comment by avimak** [comment]
@sdgalvan Braavos isn't injected in all `http` pages (aka unsecured webpages) but only in ["http://localhost/*", "https://*/*"]
try using `http://localhost` while developing and let me know if it works for you 👍

**Comment by sdgalvan** [comment]
You're right! 🔥 Thanks for help, we should close this issue right?

**Comment by avimak** [comment]
Thanks for the update. out of curiosity, what's the default http url on your dev env, 127.0.0.1?

**Comment by sdgalvan** [comment]
I use a virtual machine with Ubuntu and I access from outside it through the network, so I used the ip 192.168... and not via localhost. that was the problem.
![image](https://user-images.githubusercontent.com/58611754/209340845-effebcdb-4583-4a03-9898-54fa0a30fb43.png)
