### ISSUE TITLE
[Enhancement]: Multi chain support

### ISSUE THREAD

**Issue by avimak** [starknet-io/get-starknet#45]
1. Allow dapps to `connect` to a specific chain
2. Allow dapps to add a custom chain via [wallet_addEthereumChain](https://eips.ethereum.org/EIPS/eip-3085) 
3. Allow dapps to to switch chains via [wallet_switchEthereumChain](https://docs.metamask.io/guide/rpc-api.html#usage-with-wallet-switchethereumchain)
4. support `chainChanged` event

**Comment by dhruvkelawala** [comment]
@avimak https://github.com/argentlabs/argent-x/pull/639 Check this out. We are already working on the things you mentioned about. Should be done by the end of this week.

**Comment by dhruvkelawala** [comment]
You want me to `use wallet_addEthereumChain`? I have used `wallet_addStarknetChain` intentionally. I have read [eip-3085](https://eips.ethereum.org/EIPS/eip-3085). If @janek26 and other wants, we can change it to the standard as described by eip-3085. But as we have different API, not 1:1 like using `baseURL` and `id`, I think it's okay to use a Starknet Specific name.

**Comment by janek26** [comment]
Hey! As @dhruvkelawala mentioned adding an Ethereum chain vs adding a starknet chain rely on different details.
I think it's best to clearly separate those methods by naming, as they rely on different cryptographic curves aswell. You could imagine an EVM compatible RPC endpoint on Starknet in the future, and it would be nice to have the native namings available to them in that case.

**Comment by avimak** [comment]
thanks @janek26 , could u guys pls elaborate on the following diff from [eip-3085](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-3085.md)?

```
// new fields; why are they needed and what's their alternative on L1
id: string;
baseUrl: string;
accountImplementation?: string;
```

`rpcUrl?: string;` vs `rpcUrls?: string[];` (L1's)
`blockExplorerUrl?: string;` vs `blockExplorerUrls?: string` (L1's)

**Comment by ltoussaint** [comment]
> thanks @janek26 , could u guys pls elaborate on the following diff from [eip-3085](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-3085.md)?
> 
> ```
> // new fields; why are they needed and what's their alternative on L1
> id: string;
> baseUrl: string;
> accountImplementation?: string;
> ```
> 
> `rpcUrl?: string;` vs `rpcUrls?: string[];` (L1's)
> `blockExplorerUrl?: string;` vs `blockExplorerUrls?: string` (L1's)

@janek26 , @dhruvkelawala I'm also interested in the answer you could give to @avimak 

From what I read here is what I understand :
- `rpcUrl` is not used, so I guess it could have been removed from he code
- `baseUrl` is the equivalent to `rpcUrls` (but we provider only one url), it seems to be based on starknetjs using `baseUrl` when defining a Provider.  
_As a note about using a list of rpcUrls or a single url, from what I saw on MetaMask, they use the first valid url from the list, so I don't really understand why to propose a list_

**Comment by abdelhamidbakhta** [comment]
Hey guys, please note that as discussed with Louis we initiated the SIMPs repository.
Feel free to start a simp and include this issue as the discussion link of the SIMP.
https://github.com/CairOpen/SIMPs

**Comment by ltoussaint** [comment]
> Hey guys, please note that as discussed with Louis we initiated the SIMPs repository. Feel free to start a simp and include this issue as the discussion link of the SIMP. https://github.com/CairOpen/SIMPs

I'm working on it, among other SIMPs. :slightly_smiling_face:
Coming very soon.

**Comment by avimak** [comment]
Implemented in v2 branch
